## NumPy 字节交换

- 在几乎所有的机器上，多字节对象都被存储为连续的字节序列。字节顺序，是跨越多字节的程序对象的存储规则。
- 大端模式：指数据的高字节保存在内存的低地址中，而数据的低字节保存在内存的高地址中，这样的存储模式有点儿类似于把数据当作字符串顺序处理：地址-   由小向大增加，而数据从高位往低位放；这和我们的阅读习惯一致。

- 小端模式：指数据的高字节保存在内存的高地址中，而数据的低字节保存在内存的低地址中，这种存储模式将地址的高低和数据位权有效地结合起来，高地址   部分权值高，低地址部分权值低。

In [1]:
# numpy.ndarray.byteswap() 函数将 ndarray 中每个元素中的字节进行大小端转换。
import numpy as np 
 
a = np.array([1,  256,  8755], dtype = np.int16)  
print ('我们的数组是：')
print (a)
print ('以十六进制表示内存中的数据：')
print (map(hex,a))
# byteswap() 函数通过传入 true 来原地交换 
print ('调用 byteswap() 函数：')
print (a.byteswap(True))
print ('十六进制形式：')
print (map(hex,a))
# 我们可以看到字节已经交换了

我们的数组是：
[   1  256 8755]
以十六进制表示内存中的数据：
调用 byteswap() 函数：
[  256     1 13090]
十六进制形式：


In [2]:
import numpy as np 
 
a = np.arange(6)  
print ('我们的数组是：')
print (a)
print ('调用 id() 函数：')
print (id(a))
print ('a 赋值给 b：')
b = a 
print (b)
print ('b 拥有相同 id()：')
print (id(b))
print ('修改 b 的形状：')
b.shape =  3,2  
print (b)
print ('a 的形状也修改了：')
print (a)

我们的数组是：
[0 1 2 3 4 5]
调用 id() 函数：
4398938512
a 赋值给 b：
[0 1 2 3 4 5]
b 拥有相同 id()：
4398938512
修改 b 的形状：
[[0 1]
 [2 3]
 [4 5]]
a 的形状也修改了：
[[0 1]
 [2 3]
 [4 5]]


In [3]:
# ndarray.view() 方会创建一个新的数组对象，该方法创建的新数组的维数更改不会更改原始数据的维数。
import numpy as np 
 
# 最开始 a 是个 3X2 的数组
a = np.arange(6).reshape(3,2)  
print ('数组 a：')
print (a)
print ('创建 a 的视图：')
b = a.view()  
print (b)
print ('两个数组的 id() 不同：')
print ('a 的 id()：')
print (id(a))
print ('b 的 id()：' )
print (id(b))
# 修改 b 的形状，并不会修改 a
b.shape =  2,3
print ('b 的形状：')
print (b)
print ('a 的形状：')
print (a)

数组 a：
[[0 1]
 [2 3]
 [4 5]]
创建 a 的视图：
[[0 1]
 [2 3]
 [4 5]]
两个数组的 id() 不同：
a 的 id()：
4398939152
b 的 id()：
4398939072
b 的形状：
[[0 1 2]
 [3 4 5]]
a 的形状：
[[0 1]
 [2 3]
 [4 5]]


In [6]:
# 使用切片创建视图修改数据会影响到原始数组：
import numpy as np 
arr = np.arange(12)
print ('我们的数组：')
print (arr)
print ('创建切片：')
a=arr[3:]
b=arr[3:]
a[1]=123
b[2]=234
print(arr)
print(id(a),id(b),id(arr[3:]))

我们的数组：
[ 0  1  2  3  4  5  6  7  8  9 10 11]
创建切片：
[  0   1   2   3 123 234   6   7   8   9  10  11]
4398981408 4398981248 4398939952


In [8]:
# ndarray.copy() 函数创建一个副本。 对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置。
import numpy as np 
a = np.array([[10,10],  [2,3],  [4,5]])  
print ('数组 a：')
print (a)
print ('创建 a 的深层副本：')
b = a.copy()  
print ('数组 b：')
print (b)
# b 与 a 不共享任何内容  
print ('我们能够写入 b 来写入 a 吗？')
print (b is a)
print ('修改 b 的内容：')
b[0,0]  =  100  
print ('修改后的数组 b：')
print (b)
print ('a 保持不变：')
print (a)

数组 a：
[[10 10]
 [ 2  3]
 [ 4  5]]
创建 a 的深层副本：
数组 b：
[[10 10]
 [ 2  3]
 [ 4  5]]
我们能够写入 b 来写入 a 吗？
False
修改 b 的内容：
修改后的数组 b：
[[100  10]
 [  2   3]
 [  4   5]]
a 保持不变：
[[10 10]
 [ 2  3]
 [ 4  5]]


## 简单总结就是：
- python对列表通过切片得到的新列表进行更改，不影响原始列表
- python对数组通过切片得到的新数组进行更改，会影响原始列表

In [9]:
import numpy.matlib 
import numpy as np
print (np.matlib.empty((2,2)))
# 填充为随机数据

[[ 2.14556778e-314 -1.35311969e-315]
 [ 2.16499151e-314  2.14826068e-314]]


## NumPy 矩阵库(Matrix)
- NumPy 中包含了一个矩阵库 numpy.matlib，该模块中的函数返回的是一个矩阵，而不是 ndarray 对象。

- 一个 的矩阵是一个由行（row）列（column）元素排列成的矩形阵列

In [16]:
import numpy.matlib 
import numpy as np 
 
print(np.matlib.zeros((2,2)))
print('\n')
print(np.matlib.ones((2,2)))
print('\n')
print(np.matlib.eye(n=3, M=4, k=0, dtype=float))


[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [18]:
# numpy.matlib.identity()
# numpy.matlib.identity() 函数返回给定大小的单位矩阵。
# 单位矩阵是个方阵，从左上角到右下角的对角线（称为主对角线）上的元素均为 1，除此以外全都为 0。
import numpy.matlib 
import numpy as np 
 
# 大小为 5，类型位浮点型
print(np.matlib.identity(5, dtype=float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# numpy.matlib.rand() 函数创建一个给定大小的矩阵，数据是随机填充0-1之间的值。
import numpy.matlib 
import numpy as np 
 
print (np.matlib.rand(3,3))

[[0.11542829 0.65620457 0.01859913]
 [0.17532527 0.22507514 0.0813146 ]
 [0.54067183 0.28768846 0.16056824]]


In [24]:
# 矩阵总是二维的，而 ndarray 是一个 n 维数组。 两个对象都是可互换的。
import numpy.matlib 
import numpy as np  
 
i = np.matrix('1,2;3,4')  
print (i)
print('\n')
j = np.asarray(i)  
print (j)
print('\n')
k = np.asmatrix (j)  
print (k)

[[1 2]
 [3 4]]


[[1 2]
 [3 4]]


[[1 2]
 [3 4]]


## NumPy 线性代数
- NumPy 提供了线性代数函数库 linalg，该库包含了线性代数所需的所有功能，可以看看下面的说明：
- dot	    两个数组的点积，即元素对应相乘。
- vdot	    两个向量的点积
- inner	    两个数组的内积
- matmul	两个数组的矩阵积
- determinant	数组的行列式
- solve	    求解线性矩阵方程
- inv	    计算矩阵的乘法逆矩阵

In [27]:
# numpy.dot() 对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；
# 对于二维数组，计算的是两个数组的矩阵乘积；对于多维数组，它的通用计算公式如下，
# 即结果数组中的每个元素都是：数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和：
# dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])。
import numpy.matlib
import numpy as np
 
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print('\n')
print(b)
print('\n')
print(np.dot(a,b))

[[1 2]
 [3 4]]


[[11 12]
 [13 14]]


[[37 40]
 [85 92]]


In [28]:
# numpy.vdot() 函数是两个向量的点积。 如果第一个参数是复数，那么它的共轭复数会用于计算。 如果参数是多维数组，它会被展开。
import numpy as np 
 
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
 
# vdot 将数组展开计算内积
print (np.vdot(a,b)) # 计算式为1*11 + 2*12 + 3*13 + 4*14 

130


In [29]:
# numpy.inner() 函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。
import numpy as np 
a = np.array([1,2,3])
b = np.array([0,1,0])
print (np.inner(a,b))
# 等价于 1*0+2*1+3*0

2


In [30]:
import numpy as np 
 
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print(np.inner(a,b))#a数组第一行乘以b数组1，2行，对应元素相乘求和，得到第一行。a数组第二行乘以b数组1，2行，对应元素相乘求和，得到第二行


[[35 41]
 [81 95]]


In [31]:
# numpy.matmul 函数返回两个数组的矩阵乘积。 虽然它返回二维数组的正常乘积，但如果任一参数的维数大于2，
# 则将其视为存在于最后两个索引的矩阵的栈，并进行相应广播。
# 另一方面，如果任一参数是一维数组，则通过在其维度上附加 1 来将其提升为矩阵，并在乘法之后被去除。
# 对于二维数组，它就是矩阵乘法：
import numpy.matlib 
import numpy as np 
 
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))

[[4 1]
 [2 2]]


In [32]:
# 二维和一维运算：
import numpy.matlib 
import numpy as np 
 
a = [[1,0],[0,1]] 
b = [1,2] 
print (np.matmul(a,b)) 
print (np.matmul(b,a))
# 讲数组广播成2维数组，第二行与第一行一样。

[1 2]
[1 2]


In [35]:
# 维度大于2的数组
import numpy.matlib 
import numpy as np 
 
a = np.arange(8).reshape(2,2,2) 
print(a)
print('\n')
b = np.arange(4).reshape(2,2)
print(b)
print('\n')
print (np.matmul(a,b)) # a里面的每一个二维数组，单独与b二维数组进行正常矩阵乘法运算 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[[0 1]
 [2 3]]


[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


In [38]:
# numpy.linalg.det() 函数计算输入矩阵的行列式。
# 行列式在线性代数中是非常有用的值。 它从方阵的对角元素计算。 对于 2×2 矩阵，它是左上和右下元素的乘积与其他两个的乘积的差。
# 换句话说，对于矩阵[[a，b]，[c，d]]，行列式计算为 ad-bc。 较大的方阵被认为是 2×2 矩阵的组合。
import numpy as np
a = np.array([[1,2], [3,4]]) 
print (np.linalg.det(a))

-2.0000000000000004


In [37]:
import numpy as np
 
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print (b)
print (np.linalg.det(b))
print (6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


In [ ]:
# numpy.linalg.solve() 函数给出了矩阵形式的线性方程的解。


In [39]:
# numpy.linalg.inv()
# numpy.linalg.inv() 函数计算矩阵的乘法逆矩阵。
# 逆矩阵（inverse matrix）：设A是数域上的一个n阶矩阵，若在相同数域上存在另一个n阶矩阵B，
# 使得： AB=BA=E ，则我们称B是A的逆矩阵，而A则被称为可逆矩阵。注：E为单位矩阵。
import numpy as np 
 
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x)
print (y)
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## NumPy IO
- Numpy 可以读写磁盘上的文本数据或二进制数据。
- NumPy 为 ndarray 对象引入了一个简单的文件格式：npy。
- npy 文件用于存储重建 ndarray 所需的数据、图形、dtype 和其他信息。
- 常用的 IO 函数有：
    - load() 和 save() 函数是读写文件数组数据的两个主要函数，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为 .npy 的文件中。
    - savze() 函数用于将多个数组写入文件，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为 .npz 的文件中。
    - loadtxt() 和 savetxt() 函数处理正常的文本文件(.txt 等)

In [42]:
import numpy as np
a = np.array([1,2,3,4])
np.save('outfile.npy',a)
np.save('outfile2',a)


In [43]:
import numpy as np 
 
b = np.load('outfile.npy')  
print (b)

[1 2 3 4]


In [50]:
# numpy.savez() 函数将多个数组保存到以 npz 为扩展名的文件中。
import numpy as np 
 
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c = np.sin(b)
np.savez('manyarray.npz',a, b, sin_array=c)
r = np.load('manyarray.npz')
print(r.files)
print(r['arr_0'])
print('\n')
print(r['arr_1'])
print('\n')
print(r['sin_array'])

['sin_array', 'arr_0', 'arr_1']
[[1 2 3]
 [4 5 6]]


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]


In [53]:
# savetxt() 函数是以简单的文本文件格式存储数据，对应的使用 loadtxt() 函数来获取数据。
import numpy as np 
a=np.arange(0,10,0.5).reshape(4,-1)
print(a)
print('\n')
np.savetxt("out.txt",a,fmt="%d",delimiter=",") # 改为保存为整数，以逗号分隔
b = np.loadtxt("out.txt",delimiter=",") # load 时也要指定为逗号分隔
print(b)

[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]


[[0. 0. 1. 1. 2.]
 [2. 3. 3. 4. 4.]
 [5. 5. 6. 6. 7.]
 [7. 8. 8. 9. 9.]]


In [58]:
import numpy as np 
a=np.arange(0,10,0.5).reshape(4,-1) #只需给定行数即可，列数输入-1，它会自动帮你计算合适的列数
print(a)

[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]
