In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


In [4]:
# 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：
import numpy as np
a = np.array([[10,20,30,40],
              [50,60,70,80],
              [30,40,50,60]])
b = np.array([[1,2,3,4]])
bb = np.tile(b, (4, 1)) # 重复四次

print(a+b)
print('\n')
print(bb)

[[11 22 33 44]
 [51 62 73 84]
 [31 42 53 64]]


[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


## NumPy 迭代数组
- NumPy 迭代器对象numpy.nditer提供了灵活访问数组元素的方法
- 迭代器最基本的任务可以完成对数组对访问

In [2]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
print('\n')
for x in np.nditer(a):
    print(x)

[[0 1 2]
 [3 4 5]]


0
1
2
3
4
5


In [18]:
# 可以看出a 和 a.T 的遍历顺序是一样的，也就是他们在内存中的存储顺序也是一样的
# 但是 a.T.copy(order = 'C') 的遍历结果是不同的，那是因为它和前两种的存储方式是不一样的，默认是按行访问。
import numpy as np
a = np.arange(6).reshape(2,3)
for x in np.nditer(a):
    print(x,end=',')
print('\n')
for y in np.nditer(a.T):
    print(y,end=',')
print('\n',10*"==")
for z in np.nditer(a.T.copy(order='C')):
    print(z,end=',')
print('\n')
for w in np.nditer(a.T.copy(order='F')):
    print(w,end=',')

0,1,2,3,4,5,

0,1,2,3,4,5,
0,3,1,4,2,5,

0,1,2,3,4,5,

In [12]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
print('\n')
print(a.T)
print('=============')
print(a.T.copy(order='C'))
print('\n')
print(a.T.copy(order='F'))
print('=============')
print(a.copy(order='C'))
print('\n')
print(a.copy(order='F'))

[[0 1 2]
 [3 4 5]]


[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


[[0 3]
 [1 4]
 [2 5]]
[[0 1 2]
 [3 4 5]]


[[0 1 2]
 [3 4 5]]


In [19]:
# 可以通过显式设置，来强制 nditer 对象使用某种顺序：
# 早说嘛，这种方式不是很好理解吗
import numpy as np
a = np.arange(0,60,5).reshape(3,4)
print(a)
print('\n')
for x in np.nditer(a,order='C'):
    print(x,end=',')
print('\n',10*"==")
for y in np.nditer(a,order='F'):
    print(y,end=',')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


0,5,10,15,20,25,30,35,40,45,50,55,
0,20,40,5,25,45,10,30,50,15,35,55,

## 遍历数组时还可以修改数组中元素的值
- nditer 对象有另一个可选参数 op_flags。 默认情况下，nditer 将视待迭代遍历的数组为只读对象（read-only），
- 为了在遍历数组的同时，实现对数组元素值得修改，必须指定 read-write 或者 write-only 的模式。

In [20]:
import numpy as np
a = np.arange(0,60,5).reshape(3,4)
print(a)
print('\n')
for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = 2*x
print('修改后的数组如下\n')
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组如下

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


## nditer类的构造器拥有flags参数，它可以接受下列值：
- c_index	可以跟踪 C 顺序的索引
- f_index	可以跟踪 Fortran 顺序的索引
- multi-index	每次迭代可以跟踪一种索引类型
- external_loop	给出的值是具有多个值的一维数组，而不是零维数组

In [25]:
import numpy as np
a = np.arange(0,60,5).reshape(3,4)
print(a)
print('\n')
for x in np.nditer(a,flags=['external_loop'],order='C'):
    print(x,end=',')    
print('\n')
for x in np.nditer(a,flags=['external_loop'],order='F'):
    print(x,end=',')    

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


[ 0  5 10 15 20 25 30 35 40 45 50 55],

[ 0 20 40],[ 5 25 45],[10 30 50],[15 35 55],

In [29]:
import numpy as np
a = np.arange(0,60,5).reshape(3,4)
print(a)
print('\n')
for x in np.nditer(a,flags=['c_index'],order='C'):
    print(x,end=',')    
print('\n')
for x in np.nditer(a,flags=['f_index'],order='F'):
    print(x,end=',')  
print('\n')
for x in np.nditer(a,flags=['multi_index']):
    print(x,end=',') 

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


0,5,10,15,20,25,30,35,40,45,50,55,

0,20,40,5,25,45,10,30,50,15,35,55,

0,5,10,15,20,25,30,35,40,45,50,55,

## 广播迭代
- 如果两个数组是可广播的，nditer 组合对象能够同时迭代它们。 
- 假设数组 a 的维度为 3X4，数组 b 的维度为 1X4 ，则使用以下迭代器（数组 b 被广播到 a 的大小）。

In [30]:
import numpy as np
a = np.arange(0,60,5).reshape(3,4)
print(a)
print('\n')
b = np.array([1,2,3,4],dtype=int)
print(b)
print('\n')
for x,y in np.nditer([a,b]):
    print("%d:%d" % (x,y),end=',')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


[1 2 3 4]


0:1,5:2,10:3,15:4,20:1,25:2,30:3,35:4,40:1,45:2,50:3,55:4,