In [3]:
# 1、一行代码实现1--100之和
print(sum(range(1,101)))

5050


In [4]:
# 2、如何在一个函数内部修改全局变量
a = 5
def fun():
    global a
    a = 8
fun()
print(a)

8


In [ ]:
# 3、列出5个python标准库
os:提供了不少与操作系统相关联的函数
sys：通常用于命令行参数
re：正则匹配
math：数学运算
datetime：处理日期时间

In [7]:
# 4、字典如何删除键和合并两个字典
dic = {'a':1,'b':2}
del dic['a']
print(dic)
dic2 = {'a':1}
dic.update(dic2)
print(dic)

{'b': 2}
{'b': 2, 'a': 1}


In [8]:
# 5、谈下python的GIL
# GIL 是python的全局解释器锁，同一进程中假如有多个线程运行，一个线程在运行python程序的时候会霸占python解释器，使该进程内的其他线程无法运行
# 等该线程运行完后其他线程才能运行。如果线程运行过程中遇到耗时操作，则解释器锁解开，使其他线程运行。所以在多线程中，线程的运行仍是有先后顺序的，
# 并不是同时进行。

# 多进程中因为每个进程都能被系统分配资源，相当于每个进程有了一个python解释器，所以多进程可以实现多个进程的同时运行，缺点是进程系统资源开销大


In [12]:
# 6、python实现列表去重的方法
# 先通过集合去重，在转列表
lis = [1,1,2,2,3,3]
s = set(lis)
print(s) # s是集合
lis2 = list(s)
# 或者
lis3 = [x for x in s]
print(lis2)
print(lis3)

{1, 2, 3}
[1, 2, 3]
[1, 2, 3]


In [ ]:
# 7、fun(*args,**kwargs)中的*args,**kwargs什么意思？


In [ ]:
# 8、python2和python3的range（100）的区别
# python2返回列表，python3返回迭代器，节约内存

In [ ]:
# 9、一句话解释什么样的语言能够用装饰器?
# 函数可以作为参数传递的语言，可以使用装饰器

In [ ]:
# 10、python内建数据类型有哪些
# 整型--int
# 布尔型--bool
# 字符串--str
# 列表--list
# 元组--tuple
# 字典--dict

In [ ]:
# 11、简述面向对象中__new__和__init__区别

In [ ]:
# 12、简述with方法打开处理文件帮我我们做了什么？

In [16]:
# 13、列表[1,2,3,4,5],请使用map()函数输出[1,4,9,16,25]，并使用列表推导式提取出大于10的数，最终输出[16,25]
lis = [1,2,3,4,5]
def fun(x):
    return x**2
res = map(fun,lis)
print(type(res))
print(res)
print(list(res)) # 需要加一个list才可以，类似于zip函数
res2 = [i for i in res if i>10]
print(res2)

<class 'map'>
[1, 4, 9, 16, 25]
[]


In [25]:
# 14、python中生成随机整数、随机小数、0--1之间小数方法
import numpy as np
import random
res1 = random.randint(3,9) # 只接受两个参数。不可以设置一次性生成多个整数
print(res1)
res2 = np.random.randint(3,8,5) # 接受三个参数。可以设置一次性生成多个整数
print(res2)
res3 = np.random.rand(3,3) # 3*3的0-1的数据
print(res3)
print('\n')
res4 = np.random.random((3,3)) # 个np.random.rand函数列有不同，参数的写法不一样
print(res4)
res5 = random.random() # 生成0-1随机小数
print(res5)
res6 = np.random.rand()
print(res6)

8
[5 4 7 3 4]
[[0.7827607  0.86924488 0.0239094 ]
 [0.38157969 0.40155094 0.0903848 ]
 [0.5159441  0.35092986 0.30788589]]


[[0.36069012 0.21986274 0.12114287]
 [0.74311616 0.80447089 0.59726866]
 [0.54485472 0.80912521 0.20615505]]
0.991233194519725
0.4911064342071486


In [ ]:
# 15、避免转义给字符串加哪个字母表示原始字符串？
r , 表示需要原始字符串，不转义特殊字符

In [27]:
# 16、<div class="nam">中国</div>，用正则匹配出标签里面的内容（“中国”），其中class的类名是不确定的
import re
str = '<div class="nam">中国</div>'
res = re.findall(r'<div class=".*">(.*?)</div>', str)
print(res)

['中国']


In [29]:
# 17、python中断言方法举例
# assert（）方法，断言成功，则程序继续执行，断言失败，则程序报错
a = 4
assert(a>2)
print('断言成功')
b = 15
assert(b>10)
print('断言成功')

断言成功
断言成功


In [ ]:
# 18、数据表student有id,name,score,city字段，其中name中的名字可有重复，需要消除重复行,请写sql语句
select distinct name from student

In [ ]:
# 19、10个Linux常用命令
ls pwd cd touch rm mkdir tree cp mv cat more grep echo

## 20、python2和python3区别？列举5个

- 1、Python3 使用 print 必须要以小括号包裹打印内容，比如 print('hi')

- Python2 既可以使用带小括号的方式，也可以使用一个空格来分隔打印内容，比 如 print 'hi'

- 2、python2 range(1,10)返回列表，python3中返回迭代器，节约内存

- 3、python2中使用ascii编码，python中使用utf-8编码，
- python2默认编码为ASCII，这就是为什么我们在编写代码出现中文时需要在第一行加上#coding=utf-8

- 4、python2中unicode表示字符串序列，str表示字节序列

- python3中str表示字符串序列，byte表示字节序列

- 5、python2中为正常显示中文，引入coding声明，python3中不需要

- 6、python2中是raw_input()函数，python3中是input()函数